version: "3.8"

volumes:
  postgres_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
    container_name: post_db
    networks:
      - php_advanced

  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080
    container_name: admin_panel
    networks:
      - php_advanced

  php:
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8081:80
    networks:
      - php_advanced